# Interactive first-run: writes .env, optionally installs Python/npm deps and starts the API.
# Run from the extracted repo folder (same folder as pyproject.toml):
#   powershell -ExecutionPolicy Bypass -File .\Setup-ShieldAI.ps1
# Or double-click may work if execution policy allows.

param(
  [switch]$SkipInstall,
  [switch]$SkipStart
)

$ErrorActionPreference = "Stop"
$repoRoot = $PSScriptRoot
if (-not $repoRoot) {
  $repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
}

Set-Location $repoRoot

function Write-EnvFile {
  param(
    [string]$Path,
    [hashtable]$Vars
  )
  $utf8NoBom = New-Object System.Text.UTF8Encoding $false
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.AppendLine("# Generated by Setup-ShieldAI.ps1 — edit anytime.")
  [void]$sb.AppendLine("# --- Upstream LLM ---")
  [void]$sb.AppendLine("UPSTREAM_BASE_URL=$($Vars['UPSTREAM_BASE_URL'])")
  [void]$sb.AppendLine("UPSTREAM_API_KEY=$($Vars['UPSTREAM_API_KEY'])")
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("SHIELD_INTERNAL_TOKEN=$($Vars['SHIELD_INTERNAL_TOKEN'])")
  [void]$sb.AppendLine("DASHBOARD_ORIGINS=$($Vars['DASHBOARD_ORIGINS'])")
  [void]$sb.AppendLine("VAULT_TTL_SECONDS=$($Vars['VAULT_TTL_SECONDS'])")
  [void]$sb.AppendLine("INJECTION_POLICY=$($Vars['INJECTION_POLICY'])")
  [void]$sb.AppendLine("AUDIT_SQLITE_PATH=$($Vars['AUDIT_SQLITE_PATH'])")
  [void]$sb.AppendLine("CONFIG_STORE_PATH=$($Vars['CONFIG_STORE_PATH'])")
  [void]$sb.AppendLine("SHADOW_MODE=$($Vars['SHADOW_MODE'])")
  [void]$sb.AppendLine("")
  [void]$sb.AppendLine("DEMO_CHAT_ENABLED=$($Vars['DEMO_CHAT_ENABLED'])")
  [void]$sb.AppendLine("DEMO_CHAT_DEFAULT_MODEL=$($Vars['DEMO_CHAT_DEFAULT_MODEL'])")
  [void]$sb.AppendLine("EXTRA_CORS_ORIGINS=$($Vars['EXTRA_CORS_ORIGINS'])")
  [System.IO.File]::WriteAllText($Path, $sb.ToString(), $utf8NoBom)
}

Write-Host ""
Write-Host " ShieldAI — quick setup " -ForegroundColor Black -BackgroundColor Cyan
Write-Host " Folder: $repoRoot" -ForegroundColor DarkGray
Write-Host ""

$example = Join-Path $repoRoot ".env.example"
if (-not (Test-Path $example)) {
  Write-Host "Missing .env.example — are you in the project root?" -ForegroundColor Red
  exit 1
}

$envPath = Join-Path $repoRoot ".env"
if (Test-Path $envPath) {
  $ow = Read-Host ".env already exists. Overwrite? [y/N]"
  if ($ow -notmatch '^[yY]') {
    Write-Host "Keeping existing .env. Exiting." -ForegroundColor Yellow
    exit 0
  }
}

Write-Host "Pick upstream preset (you can edit URLs/keys later in .env):" -ForegroundColor Cyan
Write-Host "  [1] OpenAI      https://api.openai.com/v1"
Write-Host "  [2] Groq        https://api.groq.com/openai/v1"
Write-Host "  [3] Ollama      http://127.0.0.1:11434/v1"
Write-Host "  [4] Type base URL yourself"
$preset = Read-Host "Choice [1-4]"
$baseUrl = "https://api.openai.com/v1"
$suggestModel = "gpt-4o-mini"
switch -Regex ($preset.Trim()) {
  '^2' {
    $baseUrl = "https://api.groq.com/openai/v1"
    $suggestModel = "llama-3.3-70b-versatile"
  }
  '^3' {
    $baseUrl = "http://127.0.0.1:11434/v1"
    $suggestModel = "llama3.2"
  }
  '^4' {
    $baseUrl = Read-Host "UPSTREAM_BASE_URL"
    if (-not $baseUrl) { $baseUrl = "https://api.openai.com/v1" }
  }
  default {
    # 1 or empty
  }
}

$inUrl = Read-Host "Upstream base URL [$baseUrl]"
if ($inUrl.Trim()) { $baseUrl = $inUrl.Trim() }

Write-Host ""
Write-Host "Paste your upstream API key (input visible). For Ollama local you can use: ollama" -ForegroundColor DarkYellow
$apiKey = Read-Host "UPSTREAM_API_KEY"
if (-not $apiKey) {
  $apiKey = ""
}

$internal = Read-Host "Internal dashboard token (SHIELD_INTERNAL_TOKEN) [dev-internal]"
if (-not $internal) { $internal = "dev-internal" }

$demo = Read-Host "Enable browser demo chat at /chat? [Y/n]"
$demoChat = if ($demo -match '^[nN]') { "false" } else { "true" }

$modelIn = Read-Host "Default model id for demo UI [$suggestModel]"
$model = if ($modelIn.Trim()) { $modelIn.Trim() } else { $suggestModel }

$cors = Read-Host "Extra CORS origins (optional, comma-separated, e.g. http://localhost:3000)"
if (-not $cors) { $cors = "" }

$dataDir = Join-Path $repoRoot "data"
if (-not (Test-Path $dataDir)) {
  New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
}

$vars = @{
  UPSTREAM_BASE_URL            = $baseUrl
  UPSTREAM_API_KEY             = $apiKey
  SHIELD_INTERNAL_TOKEN        = $internal
  DASHBOARD_ORIGINS            = "http://localhost:5173,http://127.0.0.1:5173"
  VAULT_TTL_SECONDS            = "900"
  INJECTION_POLICY             = "block"
  AUDIT_SQLITE_PATH            = "./data/shieldai_audit.db"
  CONFIG_STORE_PATH            = "./data/shieldai_config.json"
  SHADOW_MODE                  = "false"
  DEMO_CHAT_ENABLED            = $demoChat
  DEMO_CHAT_DEFAULT_MODEL      = $model
  EXTRA_CORS_ORIGINS           = $cors
}

Write-EnvFile -Path $envPath -Vars $vars
Write-Host ""
Write-Host "Wrote $envPath" -ForegroundColor Green

if ($SkipInstall) {
  Write-Host "Skipping install (-SkipInstall). Install Python deps with 'pip install -e `"./dev`"' and dashboard deps with 'npm install' in app\dashboard." -ForegroundColor Yellow
  exit 0
}

$run = Read-Host "Install Python venv + deps + spaCy model + npm (dashboard)? [Y/n]"
if ($run -match '^[nN]') {
  Write-Host "Done. Next: see README.md for configuration, or run: powershell -ExecutionPolicy Bypass -File .\scripts\start-teacher.ps1" -ForegroundColor Cyan
  exit 0
}

try {
  $py = Get-Command python -ErrorAction Stop
} catch {
  Write-Host "Python not found on PATH. Install Python 3.11+ and re-run this script." -ForegroundColor Red
  exit 1
}

$venvPy = Join-Path $repoRoot ".venv\Scripts\python.exe"
if (-not (Test-Path $venvPy)) {
  Write-Host "Creating .venv …" -ForegroundColor Cyan
  & python -m venv (Join-Path $repoRoot ".venv")
}

Write-Host "pip install -e `".[dev]`" …" -ForegroundColor Cyan
& $venvPy -m pip install -q -U pip
& $venvPy -m pip install -q -e ".[dev]"

Write-Host "spaCy model en_core_web_lg …" -ForegroundColor Cyan
& $venvPy -c "import spacy; spacy.load('en_core_web_lg')" 2>$null
if ($LASTEXITCODE -ne 0) {
  & $venvPy -m spacy download en_core_web_lg
}

$dash = Join-Path $repoRoot "app\dashboard"
if (Test-Path (Join-Path $dash "package.json")) {
  $npm = Get-Command npm -ErrorAction SilentlyContinue
  if (-not $npm) {
    Write-Host "npm not found — skipping dashboard npm install (install Node.js LTS and run: cd app\dashboard && npm install)." -ForegroundColor Yellow
  } else {
    Write-Host "npm install (dashboard) …" -ForegroundColor Cyan
    Push-Location $dash
    try {
      npm install 2>$null
      if ($LASTEXITCODE -ne 0) {
        npm install
      }
    } finally {
      Pop-Location
    }
  }
}

Write-Host ""
Write-Host "Setup finished." -ForegroundColor Green

if ($SkipStart) { exit 0 }

$start = Read-Host "Start API now on http://127.0.0.1:8888 ? [Y/n]"
if ($start -match '^[nN]') {
  Write-Host "Start later:  powershell -ExecutionPolicy Bypass -File .\scripts\start-teacher.ps1" -ForegroundColor Cyan
  Write-Host "Or dev stack:   powershell -ExecutionPolicy Bypass -File .\scripts\dev.ps1" -ForegroundColor Cyan
  exit 0
}

$apiPort = 8888
$url = "http://127.0.0.1:$apiPort/chat"
Write-Host ""
Write-Host "Starting API …  Demo: $url   Docs: http://127.0.0.1:$apiPort/docs" -ForegroundColor Green
Write-Host "Ctrl+C to stop." -ForegroundColor Yellow
Start-Sleep -Milliseconds 600
Start-Process $url
& $venvPy -m uvicorn app.proxy.main:app --host 127.0.0.1 --port $apiPort
